### ISSUE TITLE
040_bestiary undefined stuff

### ISSUE THREAD

**Issue by EPuncker** [Zbizu/forgottenserver#8]
`categoryId`
https://github.com/Zbizu/forgottenserver/blob/5af4d46538da7b91f722295be8f2b9cff365c4de/data/scripts/modules/compendium/040_bestiary.lua#L979

and `bestiaryRaceToNameMap`
https://github.com/Zbizu/forgottenserver/blob/5af4d46538da7b91f722295be8f2b9cff365c4de/data/scripts/modules/compendium/040_bestiary.lua#L995-L1002

**Comment by Zbizu** [comment]
thank you
